
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: tjt-public
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
  - 2001:55d:9065:5c00::10-2001:55d:9065:5c00::20
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: tjt-public-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - tjt-public
