apiVersion: v1
kind: Service
metadata:
  name: m5-timelapse-service
  namespace: default
spec:
  selector:
    app: m5-timelapse
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  externalIPs:
    - 10.11.10.5
  externalTrafficPolicy: Local