apiVersion: v1
kind: Service
metadata:
  name: m5-timelapse-service
  namespace: default
spec:
  selector:
    app: m5-timelapse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs:
    - 10.11.10.5