apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitwarden.com
    chart: sm-operator
    targetRevision: 1.1.0

  destination:
    destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---